"""agregando post_id a la tabla de likes

Revision ID: 538e3c85f51f
Revises: 4d04be1ec785
Create Date: 2025-08-20 02:25:52.323647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538e3c85f51f'
down_revision = '4d04be1ec785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('comments_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('comments_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
