"""empty message

Revision ID: b783343bbd34
Revises: b81a8b06786a
Create Date: 2025-07-02 23:45:01.651774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b783343bbd34'
down_revision = 'b81a8b06786a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('likes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comments_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.drop_column('comments_id')

    # ### end Alembic commands ###
