"""empty message

Revision ID: ca5f174ececa
Revises: 83d06f92443b
Create Date: 2025-06-28 18:29:38.933345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca5f174ececa'
down_revision = '83d06f92443b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('stack',
               existing_type=postgresql.ENUM('HTML', 'CSS', 'JAVASCRIPT', 'PYTHON', 'SQL', name='stack'),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=postgresql.ENUM('STUDENT', 'JUNIOR_DEV', 'MID_DEV', 'SENIOR_DEV', name='level'),
               nullable=True)
        batch_op.drop_constraint('user_gh_login_key', type_='unique')
        batch_op.drop_column('gh_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gh_login', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_gh_login_key', ['gh_login'])
        batch_op.alter_column('level',
               existing_type=postgresql.ENUM('STUDENT', 'JUNIOR_DEV', 'MID_DEV', 'SENIOR_DEV', name='level'),
               nullable=False)
        batch_op.alter_column('stack',
               existing_type=postgresql.ENUM('HTML', 'CSS', 'JAVASCRIPT', 'PYTHON', 'SQL', name='stack'),
               nullable=False)

    # ### end Alembic commands ###
